### PR TITLE
#170  remove bot

### LINKED ISSUE #170: Remove the bot
So that we have less code to maintain.

Any future bot should be external.

### PR DESCRIPTION
**Pull request by ScalaWilliam**
Closes #170.

### CODE REVIEW

**Comment by ScalaWilliam** [comment]
I thought you wanted it to stay :P

**Comment by lucasgautheron** [comment]
Take it as an approval of the patch itself, not as an agreement to merge, but I do not care so much if you want bots removed

**Comment by ScalaWilliam** [comment]
Ah generally approval is an approval to merge ;)

**Comment by ScalaWilliam** [comment]
I'll close, we can keep this around if need be.

**Pull request closed without merging**
