### PR TITLE
update SDL2 and SDL2_Image for windows

### PR DESCRIPTION
**Pull request by lucasgautheron**
## Description

Both libraries were outdated.

## How do we know this works?

We don't.

## Check List

* [ ] Tests written (if appropriate)
* [ ] Locally tested
* [ ] Documented well enough

### CODE REVIEW

**Comment by lucasgautheron** [comment]
Should
```
#undef HAVE_UNISTD_H
```
before including zconf.h apparently.

**Comment by lucasgautheron** [comment]
Actually, not sure what to do. I don't see how updating the headers should cause such breakage..

**Comment by lucasgautheron** [comment]
@ScalaWilliam OK for you to merge this into sdl2-merge ?

**Comment by ScalaWilliam** [comment]
Yes pls

**Pull request merged**
