### PR TITLE
Debug for mac. Closes #150

### LINKED ISSUE #150: Include debug symbol in Mac build when we crash?
# Feature

## What?
We get this info, it's not helpful.
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   net.cubers                    	0x000000010acf7f40 0x10ac5b000 + 642880
1   net.cubers                    	0x000000010acf45b3 0x10ac5b000 + 628147
2   net.cubers                    	0x000000010acf3a4e 0x10ac5b000 + 625230
3   net.cubers                    	0x000000010acf13e1 0x10ac5b000 + 615393
4   net.cubers                    	0x000000010acedc56 0x10ac5b000 + 601174
5   net.cubers                    	0x000000010acee084 0x10ac5b000 + 602244
6   net.cubers                    	0x000000010ad32347 0x10ac5b000 + 881479
7   net.cubers                    	0x000000010ace03d9 0x10ac5b000 + 545753
8   net.cubers                    	0x000000010acc0f08 0x10ac5b000 + 417544
9   libdyld.dylib                 	0x00007fffc5a73255 start + 1

```
## Why?
May help identify the problem more easily.

I think it's same as #143 looking at stack trace length.

### PR DESCRIPTION
**Pull request by ScalaWilliam**
#150.

### CODE REVIEW

**Comment by ScalaWilliam** [comment]
Keep or abandon?

**Comment by lucasgautheron** [comment]
What do you want ? You're our mac guy now :D

**Comment by ScalaWilliam** [comment]
how can I crash my own ac for a test of debug symbols? I think I can still use release config but keep symbols

**Comment by lucasgautheron** [comment]
raise(SIGSEGV); ?

**Comment by ScalaWilliam** [comment]
and without recompiling? 🗡

**Comment by lucasgautheron** [comment]
our game is too stable for that
:D

**Comment by ScalaWilliam** [comment]
this should do it.

**Pull request merged**
