### PR TITLE
SDL2 merge

### LINKED ISSUE #102: Port to SDL 2.x
This one is big. SDL 1 is rather deprecated and this is already causing issues on Mac OS X.

Migration guide: https://wiki.libsdl.org/MigrationGuide#SDL_1.2_to_2.0_Migration_Guide

### LINKED ISSUE #142: sdl2 gamma cannot be changed

### PR DESCRIPTION
**Pull request by ScalaWilliam**
Based on JMM's PR. 
Closes #102.
Fixes #142.

Managed to build on Linux.
Mac build fails, Windows build fails.

May need to cherry-pick the merge as there are some of stef's commits we may not be interested in.

* [x] Works on Mac
* [x] Works on Linux
* [x] Works on Windows
* [ ] Link works while game running on Windows
* [ ] Game icon is working on all systems
* [ ] Play-tested for 2 hours.
* [ ] All key binds still work
* [x] Can change vsync
* [x] Can change gamma
* [x] accuracy box working
* [ ] Ketar's 300$ received

### CODE REVIEW

**Comment by ScalaWilliam** [comment]
Fixes #101.

**Comment by lucasgautheron** [comment]
Nice!! Note that actionfps:// protocol handling was improved for the authentication involving more SDL code on windows. There was also the game icon, i improved it for AF, these need to be taken care of

**Comment by ScalaWilliam** [comment]
Sorry I don't quite understand what you're saying.

**Comment by lucasgautheron** [comment]
So frustrating can't be more specific on a f****** phone

**Comment by ScalaWilliam** [comment]
> It works on macos sierra. Here's a file: https://174-47462659-gh.circle-artifacts.com/0/Users/distiller/ActionFPS-Game/source/xcode/build/Release/actionfps.dmg

https://github.com/ActionFPS/ActionFPS-Game/issues/102#issuecomment-277513095

**Comment by lucasgautheron** [comment]
I'll need some time to go through it.
https://github.com/ActionFPS/ActionFPS-Game/pull/125/commits/07b9cae07694b706439626c3bf268ec1321ee9fb#diff-0eac24ab95e845b530e051adef18634aL1352

Please don't just delete stuff without comment and 'FIXMEs', otherwise its hard to keep track of what's to re implement. That's what I was worried about. Some off these are super important

**Comment by ScalaWilliam** [comment]
Ok.

**Comment by ScalaWilliam** [comment]
Maybe it's an old SDL2

**Comment by lucasgautheron** [comment]
Commits to check:
https://github.com/assaultcube/AC/commit/59691c07c233019f99a2398aee01642ab37edf90
https://github.com/assaultcube/AC/commit/45792bedeaf6086784a555a8ee1e5b30cfecd698

**Comment by ScalaWilliam** [comment]
Merging after discussing with @lucasgautheron that we'll just deal with the problem as it is. Whatever bugs there are we'll discover and tackle separately and keep a single line of development.

**Pull request merged**
